### ISSUE TITLE
definitions of trajectory types

### ISSUE THREAD

**Issue by ShobiStassen** [dynverse/dynbenchmark#34]
Hi, 
can you please help clarify the key difference between the tree trajectory and the multifurcation? I was looking at supplementary fig S2(a) but not quite sure how you define the bifurcation, vs multifurcation vs. tree.
so for a multifurcation, at any node one can split into any number of branches? (0 or more)
for a tree, at any node one can split into??

Thanks a lot

**Comment by rcannood** [comment]
Hey @ShobiStassen 

A multifurcation can indeed only split once, and have one or more end states.

Robrecht
