### ISSUE TITLE
 Error in devtools::install_github("dynverse/dynbenchmark/package")

### ISSUE THREAD

**Issue by pablommesas** [dynverse/dynbenchmark#35]
```
> devtools::install_github("dynverse/dynbenchmark/package")

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo dynverse/dynbenchmark@master
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:dynverse/dynbenchmark_results.git /tmp/RtmpbRc9jx/remotes2ce925b8666e8/dynverse-dynbenchmark-e16b237/package/../results
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to install 'dynbenchmark' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:dynverse/dynbenchmark_results.git /tmp/RtmpbRc9jx/remotes2ce925b8666e8/dynverse-dynbenchmark-e16b237/package/../results' had status 128
```

**Comment by rcannood** [comment]
That's an interesting error and something you should not have to be dealing with. What you /can/ do is clone the repository and install it manually by opening RStudio and hitting the Build button. 

I will come back to this issue and find a solution for this at some point.

**Comment by pablommesas** [comment]
That did the trick. Thank you!

**Comment by zhenzuo2** [comment]
devtools::install_github("dynverse/dynbenchmark/package")
Downloading GitHub repo dynverse/dynbenchmark@HEAD
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:dynverse/dynbenchmark_results.git /tmp/RtmpRCLNoJ/remotes2ea46810992b/dynverse-dynbenchmark-c3a9b10/package/../results
The authenticity of host 'github.com (140.82.112.4)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.112.4' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failed to install 'dynbenchmark' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:dynverse/dynbenchmark_results.git /tmp/RtmpRCLNoJ/remotes2ea46810992b/dynverse-dynbenchmark-c3a9b10/package/../results' had status 128

**Comment by zhenzuo2** [comment]
> devtools::install_github("dynverse/dynbenchmark/package")
> Downloading GitHub repo dynverse/dynbenchmark@HEAD
> '/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules [git@github.com](mailto:git@github.com):dynverse/dynbenchmark_results.git /tmp/RtmpRCLNoJ/remotes2ea46810992b/dynverse-dynbenchmark-c3a9b10/package/../results
> The authenticity of host 'github.com (140.82.112.4)' can't be established.
> RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'github.com,140.82.112.4' (RSA) to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Error: Failed to install 'dynbenchmark' from GitHub:
> Command failed (128)
> In addition: Warning message:
> In system(full, intern = TRUE, ignore.stderr = quiet) :
> running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules [git@github.com](mailto:git@github.com):dynverse/dynbenchmark_results.git /tmp/RtmpRCLNoJ/remotes2ea46810992b/dynverse-dynbenchmark-c3a9b10/package/../results' had status 128

> devtools::build("/storage/chen/home/zz4/dynbenchmark/package/")
✔  checking for file ‘/storage/chen/home/zz4/dynbenchmark/package/DESCRIPTION’ (1s)
─  preparing ‘dynbenchmark’: (809ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘dynbenchmark_0.1.0.9000.tar.gz’
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid uid value replaced by that for user 'nobody''
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid gid value replaced by that for user 'nobody''
   Warning: invalid gid value replaced by that for user 'nobody'

[1] "/storage/chen/home/zz4/dynbenchmark/dynbenchmark_0.1.0.9000.tar.gz"
