### ISSUE TITLE
Synthetic dataset code 

### ISSUE THREAD

**Issue by onahman** [dynverse/dynbenchmark#36]
Hi,
It would be very helpful if you could share the code you used to create the synthetic datasets.
Specifically I am interested in creating a dataset with "golden standard" trajectory.
For my understanding, you used Splatter framework in combination with a trajectory backbone. 
I can't understand how you were able to specify all of the "from" and "to" nodes by using Splatter path simulation. 
Any help / code will be appreciated!

**Comment by rcannood** [comment]
Hello @onahman,

The majority of the synthetic datasets were generated with dyngen. Our recent pre-print details the usage of this simulator. Check it out here: [https://www.biorxiv.org/content/10.1101/2020.02.06.936971v3](https://www.biorxiv.org/content/10.1101/2020.02.06.936971v3).

Kind regards,
Robrecht
