### ISSUE TITLE
Cannot install dynbenchmark using: devtools::install_github("dynverse/dynbenchmark/package")

### ISSUE THREAD

**Issue by noobCoding** [dynverse/dynbenchmark#39]
![image](https://github.com/dynverse/dynbenchmark/assets/8758768/e0368b3f-76b5-4e03-bc72-9d0a53bc5aa2)

I used Ubuntu 22.04 LTS
My session info shows that I installed all other dyn* except dynbenchmark.

![image](https://github.com/dynverse/dynbenchmark/assets/8758768/c34e7663-1a19-486f-89eb-6787f2612b32)

**Comment by rcannood** [comment]
Hi @noobCoding! 

I changed the git submodule from ssh to https. Can you try again?

Robrecht

**Comment by noobCoding** [comment]
Thanks for very quick response! It works now.
